### ISSUE TITLE
v02 double-check

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Lumenati_4-pack#1]
Dokter, None of these are critical to run protos (although your courtyard/mask issue (#12) would definitely be worth fixing). Please read through to hear my thoughts.

Thanks! 
-Pete

1) Are the part libraries consistent with eagle github repo? [NO]
comment: kicad

2) Is the proper frame with CC attribution used? [NO]
comment: needs CC in schematic

3) Is there a SparkFun Logo? [NO]
comment: needs sfe logo in schematic

4) Is there an OSHW logo? [NO]
comment: needs oshw logo in schematic

5) Is proper attribution given to the original designer? [NO]
comment: needs engineer name in schematic

6) Are the fiducials in the lower right corner? [NO]
comment: no, but I'm not sure this will be necessary on kicad designs and possibly any future designs (I just submitted the suggestion to remove this check to the repo)

7) Is the version number correct? [NO]
comment: should be v01 for first round of protos

8) Is the VCC range clearly labeled? [NO]
comment: needs acceptable input VCC range in schematic

9) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [NO]
comment: If you want production to build these protos for you, then you will need to get this all into Sparkle. If you are hand building your protos yourself, then I guess we can wait.

10) Is the bottom left corner board dimensions at 0,0? [NO]
comment: kicad is wierd about this

11) Does this board adhere to the standard manufacturing process? (Kitting time, glue curing, humidor time, etc.) [NO]
comment: keep in mind the ws2812s require a special oven profile to not damage the LEDs, these may require the same

12) Is there solder mask between pads on of 11 mil separation and greater? [NO]
comment: yeah, but it looks like your mask gap from pads (aka courtyards) have dissapeared. The mask matches your pads 1:1. Probably want to get that 4 mils gap back in there.

![image](https://cloud.githubusercontent.com/assets/601236/26224314/fec2d9de-3bde-11e7-979a-9549309baf12.png)

13) Are there fiducials on both the TOP and BOTTOM of the board? [YES]
comment: this will never see SS, so it doesn't need them on bottom

14) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [NO]
comment: needs dimensions (probably put them on Dwgs.User layer)

15) Is the CC/Design By included in tDocu? [NO]
comment: needs CC and designer in board file

**Comment by Pete-O** [comment]
1) I can't do anything about that.

2) Fixed.

3) Fixed.

4) Fixed.

5) Fixed.

6) Noted.

7) It's v02 because it's the second round of designs files. I'll make sure it's that way in the future, but I _really_ don't want to undo all of that on these first designs.

8) "VCC" isn't even defined on the schematic or the pcb. Power in is listed as 5V on the datasheet, and that's what I've specified on both the schematic and the pcb.

9) Yep, I'll have to deal with this, but I imagine I'll build the first ones.

10) Yeah, I can't do anything about that.

11) We'll have to talk about this. I'm not sure what I could add in the schematic of the pcb to accommodate. Are we just talking about notes?

12) Don't know what happened to that. Fixed now.

13) Noted.

14) Fixed.

15) Fixed.
